from .sequential import Sequential
from .lsf import LSF
from .lwf import LwF
from .ewc import EWC
from .er import ER
from .clu_er import CLU_ER
from .derpp import Derpp
from .clpu_derpp import CLPU_Derpp
from .independent import Independent
